apiVersion: v1
kind: Service
metadata:
  name: nodeport-service-nginx
  namespace: jen-ns
spec:
  clusterIP: 10.100.100.201
  clusterIPs:
  - 10.100.100.201
  ports:
  - name: web
    nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort